version: '3'
services:
  ab:
    image: "aoki/ab"
    links:
      - cache
    restart: always
    environment:
      AB_SLACK_API_TOKEN: ${AB_SLACK_API_TOKEN}
      HUBOT_CONFLUENCE_USER: ${HUBOT_CONFLUENCE_USER}
      HUBOT_CONFLUENCE_PASSWORD: ${HUBOT_CONFLUENCE_PASSWORD}
      HUBOT_CONFLUENCE_URL: ${HUBOT_CONFLUENCE_URL}
      HUBOT_JIRA_USER: ${HUBOT_JIRA_USER}
      HUBOT_JIRA_PASSWORD: ${HUBOT_JIRA_PASSWORD}
      HUBOT_JIRA_URL: ${HUBOT_JIRA_URL}
      NODE_DEBUG: ${NODE_DEBUG}
  cache:
    image: "redis:3.0.7-alpine"
    ports:
      - 6379:6379
